name: note_app
description: Note app multiplatform

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_quill: ^7.4.15
  flutter_svg: ^2.0.7
  window_manager: ^0.3.7
  flutter_launcher_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/note-icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/img/note-icon.png"
    background_color: "#483D9F"
    theme_color: "#483D9F"
  windows:
    generate: true
    image_path: "assets/img/note-icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/img/note-icon.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/icons/
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter-Bold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
    - family: Inter-Medium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
    - family: Inter-Regular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf

    - family: OpenSans-Bold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
    - family: OpenSans-BoldItalic
      fonts:
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
    - family: OpenSans-Italic
      fonts:
        - asset: assets/fonts/OpenSans-Italic.ttf
    - family: OpenSans-Regular
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Poppins-BoldItalic
      fonts:
        - asset: assets/fonts/Poppins-BoldItalic.ttf
    - family: Poppins-Italic
      fonts:
        - asset: assets/fonts/Poppins-Italic.ttf
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Roboto-BoldItalic
      fonts:
        - asset: assets/fonts/Roboto-BoldItalic.ttf
    - family: Roboto-Italic
      fonts:
        - asset: assets/fonts/Roboto-Italic.ttf
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
